" generated by unicodef: https://github.com/tsouanas/unicodef

inoremap \\bomb 💣
inoremap \\boom 💥
inoremap \\bulb 💡
inoremap \\poo 💩
inoremap \\puffy 🐡
inoremap \\tada 🎉
inoremap \\zzz 💤
inoremap \\anchor ⚓
