inoremap \\showspace ␣
inoremap \\spacechar ␣
inoremap \\nbsp  
inoremap \\~  
inoremap \\return ⏎
inoremap \\lqua ⌜
inoremap \\rqua ⌝
inoremap \\langle ⟨
inoremap \\rangle ⟩
inoremap \\lceil ⌈
inoremap \\rceil ⌉
inoremap \\lfloor ⌊
inoremap \\rfloor ⌋
inoremap \\lbag ⟅
inoremap \\rbag ⟆
inoremap \\lsem ⟦
inoremap \\rsem ⟧
inoremap \\halmos ∎
inoremap \\qed ∎
inoremap \\leq ≤
inoremap \\geq ≥
inoremap \\neq ≠
inoremap \\div |
inoremap \\ndiv ∤
inoremap \\forall ∀
inoremap \\exists ∃
inoremap \\nexists ∄
inoremap \\implies ⇒
inoremap \\implied ⇐
inoremap \\iff ⇔
inoremap \\timplies ⟹
inoremap \\timplied ⟸
inoremap \\tiff ⟺
inoremap \\vimplies ⇓
inoremap \\vimplied ⇑
inoremap \\viff ⇕
inoremap \\inteq ≡
inoremap \\defeq ≝
inoremap \\doteq ≐
inoremap \\askeq ≟
inoremap \\defiff ⇐≝⇒
inoremap \\intimplies ⇛
inoremap \\vintimplied ⤊
inoremap \\vintimplies ⤋
inoremap \\intimplied ⇚
inoremap \\leadfrom ↜
inoremap \\leadsto ↝
inoremap \\therefore ∴
inoremap \\because ∵
inoremap \\vdots ⋮
inoremap \\hdots ⋯
inoremap \\cdots ⋯
inoremap \\dotsb ⋯
inoremap \\ldots …
inoremap \\dotsc …
inoremap \\pm ±
inoremap \\mp ∓
inoremap \\infty ∞
inoremap \\pinfty +∞
inoremap \\minfty -∞
inoremap \\pminfty ±∞
inoremap \\mpinfty ∓∞
inoremap \\surd √
inoremap \\integ ∫
inoremap \\iinteg ∬
inoremap \\iiinteg ∭
inoremap \\ointeg ∮
inoremap \\nabla ∇
inoremap \\partial ∂
inoremap \\ast ∗
inoremap \\star ⋆
inoremap \\bullet ∙
inoremap \\cdot ·
inoremap \\ntimes ·
inoremap \\cross ×
inoremap \\times ×
inoremap \\circ ∘
inoremap \\oplus ⊕
inoremap \\ominus ⊖
inoremap \\otimes ⊗
inoremap \\tensor ⊗
inoremap \\ocross ⊗
inoremap \\odiv ⊘
inoremap \\odot ⊙
inoremap \\dotminus ∸
inoremap \\monus ∸
inoremap \\emptyset Ø
inoremap \\bools 𝔹
inoremap \\nats ℕ
inoremap \\ints ℤ
inoremap \\rats ℚ
inoremap \\reals ℝ
inoremap \\complex ℂ
inoremap \\notin ∉
inoremap \\in ∈
inoremap \\Inter ⋂
inoremap \\Union ⋃
inoremap \\inter ∩
inoremap \\union ∪
inoremap \\disjunion ⊎
inoremap \\Disjunion ⨄
inoremap \\subset ⊆
inoremap \\supset ⊇
inoremap \\psubset ⊊
inoremap \\psupset ⊋
inoremap \\hsubset ⊂
inoremap \\hsupset ⊃
inoremap \\nsubset ⊈
inoremap \\nsupset ⊉
inoremap \\subsetneq ⊊
inoremap \\supsetneq ⊋
inoremap \\pset ℘
inoremap \\aleph ℵ
inoremap \\beth ℶ
inoremap \\gimel ℷ
inoremap \\comp ∘
inoremap \\to →
inoremap \\from ←
inoremap \\parto ⇀
inoremap \\mapsto ↦
inoremap \\mapsfrom ↤
inoremap \\tmapsto ⟼
inoremap \\tmapsfrom ⟻
inoremap \\parfrom ↼
inoremap \\rest ↾
inoremap \\surto ↠
inoremap \\surfrom ↞
inoremap \\injto ↣
inoremap \\injfrom ↢
inoremap \\embto ↪
inoremap \\embfrom ↩
inoremap \\bijto ⤖
inoremap \\relto ⇾
inoremap \\relfrom ⇽
inoremap \\dual ∂
inoremap \\ndetfrom ⇜
inoremap \\ndetto ⇝
inoremap \\dfrom ⇠
inoremap \\dto ⇢
inoremap \\equiv ≅
inoremap \\nequiv ≇
inoremap \\rcomp ⋄
inoremap \\cong ≡
inoremap \\ncong ≢
inoremap \\normal ⊴
inoremap \\pnormal ⊲
inoremap \\Prod ∏
inoremap \\Coprod ∐
inoremap \\coprod ⨿
inoremap \\Sum ∑
inoremap \\opcat ᵒᵖ
inoremap \\cons ∷
inoremap \\:: ∷
inoremap \\lnot ¬
inoremap \\lforall ∀
inoremap \\lexists ∃
inoremap \\limplies →
inoremap \\limplied ←
inoremap \\liff ↔
inoremap \\land ∧
inoremap \\lor ∨
inoremap \\Land ⋀
inoremap \\Lor ⋁
inoremap \\sequent ⊢
inoremap \\proves ⊢
inoremap \\nproves ⊬
inoremap \\models ⊨
inoremap \\nmodels ⊭
inoremap \\forces ⊩
inoremap \\nforces ⊮
inoremap \\linnot ⊥
inoremap \\linto ⊸
inoremap \\linwith &
inoremap \\linpar ⅋
inoremap \\horseimplies ⥰
inoremap \\horseshoe ⥰
inoremap \\top ⊤
inoremap \\bottom ⊥
inoremap \\Meet ⋀
inoremap \\Join ⋁
inoremap \\meet ∧
inoremap \\join ∨
inoremap \\incompar ≸
inoremap \\incompat ‖
inoremap \\wbelow ≪
inoremap \\wabove ≫
inoremap \\domlt ⊏
inoremap \\domgt ⊐
inoremap \\domleq ⊑
inoremap \\domgeq ⊒
inoremap \\glb ⊓
inoremap \\lub ⊔
inoremap \\Glb ⨅
inoremap \\Lub ⨆
inoremap \\spades ♠
inoremap \\hearts ♡
inoremap \\diamonds ♢
inoremap \\clubs ♣
inoremap \\magic ⛤
inoremap \\rturnstile ⊢
inoremap \\lturnstile ⊣
inoremap \\sqleftarrow ⇜
inoremap \\sqrightarrow ⇝
inoremap \\sqbotharrow ↭
inoremap \\nwarrow ↖
inoremap \\nearrow ↗
inoremap \\swarrow ↙
inoremap \\searrow ↘
inoremap \\duparrow ⇡
inoremap \\drightarrow ⇢
inoremap \\ddownarrow ⇣
inoremap \\dleftarrow ⇠
inoremap \\up ↑
inoremap \\down ↓
inoremap \\Ell ℒ
inoremap \\ell ℓ
inoremap \\bang !
inoremap \\gnab ¡
inoremap \\bbang ‼
inoremap \\ibang ‽
inoremap \\ignab ⸘
inoremap \\abang ⁈
inoremap \\bask ⁉
