inoremap \\spc ␣
inoremap \\nbsp  
inoremap \\return ⏎
inoremap \\lqua ⌜
inoremap \\rqua ⌝
inoremap \\langle ⟨
inoremap \\rangle ⟩
inoremap \\lceil ⌈
inoremap \\rceil ⌉
inoremap \\lfloor ⌊
inoremap \\rfloor ⌋
inoremap \\lbag ⟅
inoremap \\rbag ⟆
inoremap \\lsem ⟦
inoremap \\rsem ⟧
inoremap \\lnorm ‖
inoremap \\rnorm ‖
inoremap \\halmos ∎
inoremap \\qed ∎
inoremap \\leq ≤
inoremap \\geq ≥
inoremap \\neq ≠
inoremap \\nlt ≮
inoremap \\ngt ≯
inoremap \\nleq ≰
inoremap \\ngeq ≱
inoremap \\div ∣
inoremap \\ndiv ∤
inoremap \\forall ∀
inoremap \\exists ∃
inoremap \\nexists ∄
inoremap \\implies ⇒
inoremap \\implied ⇐
inoremap \\iff ⇔
inoremap \\timplies ⟹
inoremap \\timplied ⟸
inoremap \\tiff ⟺
inoremap \\vimplies ⇓
inoremap \\vimplied ⇑
inoremap \\viff ⇕
inoremap \\rlarr ⇄
inoremap \\udarr ⇅
inoremap \\lrarr ⇆
inoremap \\llarr ⇇
inoremap \\uuarr ⇈
inoremap \\rrarr ⇉
inoremap \\ddarr ⇊
inoremap \\nimplied ⇍
inoremap \\nimplies ⇏
inoremap \\niff ⇎
inoremap \\inteq ≡
inoremap \\defeq ≝
inoremap \\doteq ≐
inoremap \\askeq ≟
inoremap \\defiff ⇐≝⇒
inoremap \\intimplies ⇛
inoremap \\vintimplied ⤊
inoremap \\vintimplies ⤋
inoremap \\intimplied ⇚
inoremap \\leadfrom ↜
inoremap \\leadsto ↝
inoremap \\therefore ∴
inoremap \\because ∵
inoremap \\vdots ⋮
inoremap \\hdots ⋯
inoremap \\cdots ⋯
inoremap \\dotsb ⋯
inoremap \\ldots …
inoremap \\dotsc …
inoremap \\pm ±
inoremap \\mp ∓
inoremap \\infty ∞
inoremap \\pinfty +∞
inoremap \\minfty -∞
inoremap \\pminfty ±∞
inoremap \\mpinfty ∓∞
inoremap \\surd √
inoremap \\integ ∫
inoremap \\iinteg ∬
inoremap \\iiinteg ∭
inoremap \\ointeg ∮
inoremap \\nabla ∇
inoremap \\partial ∂
inoremap \\ast ∗
inoremap \\star ⋆
inoremap \\bullet ∙
inoremap \\cdot ·
inoremap \\ntimes ·
inoremap \\cross ×
inoremap \\times ×
inoremap \\circ ∘
inoremap \\oplus ⊕
inoremap \\ominus ⊖
inoremap \\otimes ⊗
inoremap \\tensor ⊗
inoremap \\ocross ⊗
inoremap \\odiv ⊘
inoremap \\odot ⊙
inoremap \\dotminus ∸
inoremap \\monus ∸
inoremap \\uplus ⊎
inoremap \\Uplus ⨄
inoremap \\dhole –
inoremap \\hole _
inoremap \\emptyset Ø
inoremap \\bools 𝔹
inoremap \\nats ℕ
inoremap \\ints ℤ
inoremap \\rats ℚ
inoremap \\reals ℝ
inoremap \\complex ℂ
inoremap \\notin ∉
inoremap \\in ∈
inoremap \\Inter ⋂
inoremap \\Union ⋃
inoremap \\inter ∩
inoremap \\union ∪
inoremap \\disjunion ⊎
inoremap \\Disjunion ⨄
inoremap \\dunion ⊎
inoremap \\Dunion ⨄
inoremap \\symdiff ∆
inoremap \\sdiff ∆
inoremap \\setminus ∖
inoremap \\minus ∖
inoremap \\subset ⊆
inoremap \\supset ⊇
inoremap \\psubset ⊊
inoremap \\psupset ⊋
inoremap \\hsubset ⊂
inoremap \\hsupset ⊃
inoremap \\nsubset ⊈
inoremap \\nsupset ⊉
inoremap \\subsetneq ⊊
inoremap \\supsetneq ⊋
inoremap \\sqleq ⊑
inoremap \\sqgeq ⊒
inoremap \\sqlt ⊏
inoremap \\sqgt ⊐
inoremap \\sqlneq ⋤
inoremap \\sqgneq ⋥
inoremap \\sqnleq ⋢
inoremap \\sqngeq ⋣
inoremap \\semleq ⊑
inoremap \\semgeq ⊒
inoremap \\semlneq ⋤
inoremap \\semgneq ⋥
inoremap \\nsemleq ⋢
inoremap \\nsemgeq ⋣
inoremap \\domleq ⊑
inoremap \\domgeq ⊒
inoremap \\domlneq ⋤
inoremap \\domgneq ⋥
inoremap \\pset ℘
inoremap \\aleph ℵ
inoremap \\beth ℶ
inoremap \\gimel ℷ
inoremap \\comp ∘
inoremap \\to →
inoremap \\from ←
inoremap \\nto ↛
inoremap \\nfrom ↚
inoremap \\parto ⇀
inoremap \\mapsto ↦
inoremap \\mapsfrom ↤
inoremap \\tmapsto ⟼
inoremap \\tmapsfrom ⟻
inoremap \\mapsup ↥
inoremap \\mapsdown ↧
inoremap \\parfrom ↼
inoremap \\rest ↾
inoremap \\surto ↠
inoremap \\surfrom ↞
inoremap \\injto ↣
inoremap \\injfrom ↢
inoremap \\embto ↪
inoremap \\embfrom ↩
inoremap \\bijto ⤖
inoremap \\relto ⇾
inoremap \\relfrom ⇽
inoremap \\dual ∂
inoremap \\ndetfrom ⇜
inoremap \\ndetto ⇝
inoremap \\dfrom ⇠
inoremap \\dto ⇢
inoremap \\equiv ≅
inoremap \\nequiv ≇
inoremap \\rcomp ⋄
inoremap \\cong ≡
inoremap \\ncong ≢
inoremap \\normal ⊴
inoremap \\pnormal ⊲
inoremap \\sim ~
inoremap \\nsim ≁
inoremap \\approx ≈
inoremap \\napprox ≉
inoremap \\Prod ∏
inoremap \\Coprod ∐
inoremap \\coprod ⨿
inoremap \\Sum ∑
inoremap \\op ᵒᵖ
inoremap \\cons ∷
inoremap \\concat ⧺
inoremap \\:: ∷
inoremap \\inv ⁻¹
inoremap \\lnot ¬
inoremap \\lforall ∀
inoremap \\lexists ∃
inoremap \\limplies →
inoremap \\limplied ←
inoremap \\liff ↔
inoremap \\land ∧
inoremap \\lor ∨
inoremap \\Land ⋀
inoremap \\Lor ⋁
inoremap \\sequent ⊢
inoremap \\proves ⊢
inoremap \\nproves ⊬
inoremap \\models ⊨
inoremap \\nmodels ⊭
inoremap \\forces ⊩
inoremap \\nforces ⊮
inoremap \\linnot ⊥
inoremap \\linto ⊸
inoremap \\linwith &
inoremap \\linpar ⅋
inoremap \\himplies ⥰
inoremap \\horse ⥰
inoremap \\top ⊤
inoremap \\bottom ⊥
inoremap \\Meet ⋀
inoremap \\Join ⋁
inoremap \\meet ∧
inoremap \\join ∨
inoremap \\incompar ≸
inoremap \\incompat ‖
inoremap \\wbelow ≪
inoremap \\wabove ≫
inoremap \\domlt ⊏
inoremap \\domgt ⊐
inoremap \\domleq ⊑
inoremap \\domgeq ⊒
inoremap \\glb ⊓
inoremap \\lub ⊔
inoremap \\Glb ⨅
inoremap \\Lub ⨆
inoremap \\spades ♠
inoremap \\hearts ♡
inoremap \\diamonds ♢
inoremap \\clubs ♣
inoremap \\magic ⛤
inoremap \\rturnstile ⊢
inoremap \\lturnstile ⊣
inoremap \\sqleftarrow ⇜
inoremap \\sqrightarrow ⇝
inoremap \\sqbotharrow ↭
inoremap \\nwarrow ↖
inoremap \\nearrow ↗
inoremap \\swarrow ↙
inoremap \\searrow ↘
inoremap \\duparrow ⇡
inoremap \\drightarrow ⇢
inoremap \\ddownarrow ⇣
inoremap \\dleftarrow ⇠
inoremap \\up ↑
inoremap \\down ↓
inoremap \\Ell ℒ
inoremap \\ell ℓ
inoremap \\bang !
inoremap \\gnab ¡
inoremap \\bbang ‼
inoremap \\ibang ‽
inoremap \\ignab ⸘
inoremap \\abang ⁈
inoremap \\bask ⁉
inoremap \\CAT 𝐂𝐚𝐭
inoremap \\SET 𝐒𝐞𝐭
inoremap \\PSET 𝐏𝐒𝐞𝐭
inoremap \\FINSET 𝐅𝐢𝐧𝐒𝐞𝐭
inoremap \\FINORD 𝐅𝐢𝐧𝐎𝐫𝐝
inoremap \\ORD 𝐎𝐫𝐝
inoremap \\POSET 𝐏𝐨𝐬𝐞𝐭
inoremap \\SGROUP 𝐒𝐞𝐦𝐢𝐠𝐫𝐨𝐮𝐩
inoremap \\SGRP 𝐒𝐞𝐦𝐢𝐠𝐫𝐩
inoremap \\MON 𝐌𝐨𝐧
inoremap \\MONOID 𝐌𝐨𝐧𝐨𝐢𝐝
inoremap \\GROUP 𝐆𝐫𝐨𝐮𝐩
inoremap \\GRP 𝐆𝐫𝐩
inoremap \\ABEL 𝐀𝐛𝐞𝐥
inoremap \\RING 𝐑𝐢𝐧𝐠
inoremap \\RNG 𝐑𝐧𝐠
inoremap \\RIG 𝐑𝐢𝐠
inoremap \\MOD 𝐌𝐨𝐝
inoremap \\MAT 𝐌𝐚𝐭𝐫𝐢𝐱
inoremap \\LAT 𝐋𝐚𝐭𝐭𝐢𝐜𝐞
inoremap \\HALG 𝐇𝐞𝐲𝐭𝐢𝐧𝐠
inoremap \\BALG 𝐁𝐨𝐨𝐥𝐞𝐚𝐧
inoremap \\HA 𝐇𝐀
inoremap \\BA 𝐁𝐀
