inoremap \\bomb 💣
inoremap \\boom 💥
inoremap \\bulb 💡
inoremap \\hrmf ⍨
inoremap \\pirate ☠
inoremap \\poo 💩
inoremap \\smooch ⍣
inoremap \\zzz 💤
inoremap \\scrA 𝒜
inoremap \\scrB ℬ
inoremap \\scrC 𝒞
inoremap \\scrD 𝒟
inoremap \\scrE ℰ
inoremap \\scrF ℱ
inoremap \\scrG 𝒢
inoremap \\scrH ℋ
inoremap \\scrI ℐ
inoremap \\scrJ 𝒥
inoremap \\scrK 𝒦
inoremap \\scrL ℒ
inoremap \\scrM ℳ
inoremap \\scrN 𝒩
inoremap \\scrO 𝒪
inoremap \\scrP 𝒫
inoremap \\scrQ 𝒬
inoremap \\scrR ℛ
inoremap \\scrS 𝒮
inoremap \\scrT 𝒯
inoremap \\scrU 𝒰
inoremap \\scrV 𝒱
inoremap \\scrW 𝒲
inoremap \\scrX 𝒳
inoremap \\scrY 𝒴
inoremap \\scrZ 𝒵
inoremap \\scra 𝒶
inoremap \\scrb 𝒷
inoremap \\scrc 𝒸
inoremap \\scrd 𝒹
inoremap \\scre ℯ
inoremap \\scrf 𝒻
inoremap \\scrg ℊ
inoremap \\scrh 𝒽
inoremap \\scri 𝒾
inoremap \\scrj 𝒿
inoremap \\scrk 𝓀
inoremap \\scrl 𝓁
inoremap \\scrm 𝓂
inoremap \\scrn 𝓃
inoremap \\scro ℴ
inoremap \\scrp 𝓅
inoremap \\scrq 𝓆
inoremap \\scrr 𝓇
inoremap \\scrs 𝓈
inoremap \\scrt 𝓉
inoremap \\scru 𝓊
inoremap \\scrv 𝓋
inoremap \\scrw 𝓌
inoremap \\scrx 𝓍
inoremap \\scry 𝓎
inoremap \\scrz 𝓏
inoremap \\calA 𝓐
inoremap \\calB 𝓑
inoremap \\calC 𝓒
inoremap \\calD 𝓓
inoremap \\calE 𝓔
inoremap \\calF 𝓕
inoremap \\calG 𝓖
inoremap \\calH 𝓗
inoremap \\calI 𝓘
inoremap \\calJ 𝓙
inoremap \\calK 𝓚
inoremap \\calL 𝓛
inoremap \\calM 𝓜
inoremap \\calN 𝓝
inoremap \\calO 𝓞
inoremap \\calP 𝓟
inoremap \\calQ 𝓠
inoremap \\calR 𝓡
inoremap \\calS 𝓢
inoremap \\calT 𝓣
inoremap \\calU 𝓤
inoremap \\calV 𝓥
inoremap \\calW 𝓦
inoremap \\calX 𝓧
inoremap \\calY 𝓨
inoremap \\calZ 𝓩
inoremap \\cala 𝓪
inoremap \\calb 𝓫
inoremap \\calc 𝓬
inoremap \\cald 𝓭
inoremap \\cale 𝓮
inoremap \\calf 𝓯
inoremap \\calg 𝓰
inoremap \\calh 𝓱
inoremap \\cali 𝓲
inoremap \\calj 𝓳
inoremap \\calk 𝓴
inoremap \\call 𝓵
inoremap \\calm 𝓶
inoremap \\caln 𝓷
inoremap \\calo 𝓸
inoremap \\calp 𝓹
inoremap \\calq 𝓺
inoremap \\calr 𝓻
inoremap \\cals 𝓼
inoremap \\calt 𝓽
inoremap \\calu 𝓾
inoremap \\calv 𝓿
inoremap \\calw 𝔀
inoremap \\calx 𝔁
inoremap \\caly 𝔂
inoremap \\calz 𝔃
inoremap \\ttA 𝙰
inoremap \\ttB 𝙱
inoremap \\ttC 𝙲
inoremap \\ttD 𝙳
inoremap \\ttE 𝙴
inoremap \\ttF 𝙵
inoremap \\ttG 𝙶
inoremap \\ttH 𝙷
inoremap \\ttI 𝙸
inoremap \\ttJ 𝙹
inoremap \\ttK 𝙺
inoremap \\ttL 𝙻
inoremap \\ttM 𝙼
inoremap \\ttN 𝙽
inoremap \\ttO 𝙾
inoremap \\ttP 𝙿
inoremap \\ttQ 𝚀
inoremap \\ttR 𝚁
inoremap \\ttS 𝚂
inoremap \\ttT 𝚃
inoremap \\ttU 𝚄
inoremap \\ttV 𝚅
inoremap \\ttW 𝚆
inoremap \\ttX 𝚇
inoremap \\ttY 𝚈
inoremap \\ttZ 𝚉
inoremap \\tta 𝚊
inoremap \\ttb 𝚋
inoremap \\ttc 𝚌
inoremap \\ttd 𝚍
inoremap \\tte 𝚎
inoremap \\ttf 𝚏
inoremap \\ttg 𝚐
inoremap \\tth 𝚑
inoremap \\tti 𝚒
inoremap \\ttj 𝚓
inoremap \\ttk 𝚔
inoremap \\ttl 𝚕
inoremap \\ttm 𝚖
inoremap \\ttn 𝚗
inoremap \\tto 𝚘
inoremap \\ttp 𝚙
inoremap \\ttq 𝚚
inoremap \\ttr 𝚛
inoremap \\tts 𝚜
inoremap \\ttt 𝚝
inoremap \\ttu 𝚞
inoremap \\ttv 𝚟
inoremap \\ttw 𝚠
inoremap \\ttx 𝚡
inoremap \\tty 𝚢
inoremap \\ttz 𝚣
inoremap \\itA 𝐴
inoremap \\itB 𝐵
inoremap \\itC 𝐶
inoremap \\itD 𝐷
inoremap \\itE 𝐸
inoremap \\itF 𝐹
inoremap \\itG 𝐺
inoremap \\itH 𝐻
inoremap \\itI 𝐼
inoremap \\itJ 𝐽
inoremap \\itK 𝐾
inoremap \\itL 𝐿
inoremap \\itM 𝑀
inoremap \\itN 𝑁
inoremap \\itO 𝑂
inoremap \\itP 𝑃
inoremap \\itQ 𝑄
inoremap \\itR 𝑅
inoremap \\itS 𝑆
inoremap \\itT 𝑇
inoremap \\itU 𝑈
inoremap \\itV 𝑉
inoremap \\itW 𝑊
inoremap \\itX 𝑋
inoremap \\itY 𝑌
inoremap \\itZ 𝑍
inoremap \\ita 𝑎
inoremap \\itb 𝑏
inoremap \\itc 𝑐
inoremap \\itd 𝑑
inoremap \\ite 𝑒
inoremap \\itf 𝑓
inoremap \\itg 𝑔
inoremap \\ith ℎ
inoremap \\iti 𝑖
inoremap \\itj 𝑗
inoremap \\itk 𝑘
inoremap \\itl 𝑙
inoremap \\itm 𝑚
inoremap \\itn 𝑛
inoremap \\ito 𝑜
inoremap \\itp 𝑝
inoremap \\itq 𝑞
inoremap \\itr 𝑟
inoremap \\its 𝑠
inoremap \\itt 𝑡
inoremap \\itu 𝑢
inoremap \\itv 𝑣
inoremap \\itw 𝑤
inoremap \\itx 𝑥
inoremap \\ity 𝑦
inoremap \\itz 𝑧
inoremap \\isA 𝘈
inoremap \\isB 𝘉
inoremap \\isC 𝘊
inoremap \\isD 𝘋
inoremap \\isE 𝘌
inoremap \\isF 𝘍
inoremap \\isG 𝘎
inoremap \\isH 𝘏
inoremap \\isI 𝘐
inoremap \\isJ 𝘑
inoremap \\isK 𝘒
inoremap \\isL 𝘓
inoremap \\isM 𝘔
inoremap \\isN 𝘕
inoremap \\isO 𝘖
inoremap \\isP 𝘗
inoremap \\isQ 𝘘
inoremap \\isR 𝘙
inoremap \\isS 𝘚
inoremap \\isT 𝘛
inoremap \\isU 𝘜
inoremap \\isV 𝘝
inoremap \\isW 𝘞
inoremap \\isX 𝘟
inoremap \\isY 𝘠
inoremap \\isZ 𝘡
inoremap \\isa 𝘢
inoremap \\isb 𝘣
inoremap \\isc 𝘤
inoremap \\isd 𝘥
inoremap \\ise 𝘦
inoremap \\isf 𝘧
inoremap \\isg 𝘨
inoremap \\ish 𝘩
inoremap \\isi 𝘪
inoremap \\isj 𝘫
inoremap \\isk 𝘬
inoremap \\isl 𝘭
inoremap \\ism 𝘮
inoremap \\isn 𝘯
inoremap \\iso 𝘰
inoremap \\isp 𝘱
inoremap \\isq 𝘲
inoremap \\isr 𝘳
inoremap \\iss 𝘴
inoremap \\ist 𝘵
inoremap \\isu 𝘶
inoremap \\isv 𝘷
inoremap \\isw 𝘸
inoremap \\isx 𝘹
inoremap \\isy 𝘺
inoremap \\isz 𝘻
inoremap \\bfA 𝐀
inoremap \\bfB 𝐁
inoremap \\bfC 𝐂
inoremap \\bfD 𝐃
inoremap \\bfE 𝐄
inoremap \\bfF 𝐅
inoremap \\bfG 𝐆
inoremap \\bfH 𝐇
inoremap \\bfI 𝐈
inoremap \\bfJ 𝐉
inoremap \\bfK 𝐊
inoremap \\bfL 𝐋
inoremap \\bfM 𝐌
inoremap \\bfN 𝐍
inoremap \\bfO 𝐎
inoremap \\bfP 𝐏
inoremap \\bfQ 𝐐
inoremap \\bfR 𝐑
inoremap \\bfS 𝐒
inoremap \\bfT 𝐓
inoremap \\bfU 𝐔
inoremap \\bfV 𝐕
inoremap \\bfW 𝐖
inoremap \\bfX 𝐗
inoremap \\bfY 𝐘
inoremap \\bfZ 𝐙
inoremap \\bfa 𝐚
inoremap \\bfb 𝐛
inoremap \\bfc 𝐜
inoremap \\bfd 𝐝
inoremap \\bfe 𝐞
inoremap \\bff 𝐟
inoremap \\bfg 𝐠
inoremap \\bfh 𝐡
inoremap \\bfi 𝐢
inoremap \\bfj 𝐣
inoremap \\bfk 𝐤
inoremap \\bfl 𝐥
inoremap \\bfm 𝐦
inoremap \\bfn 𝐧
inoremap \\bfo 𝐨
inoremap \\bfp 𝐩
inoremap \\bfq 𝐪
inoremap \\bfr 𝐫
inoremap \\bfs 𝐬
inoremap \\bft 𝐭
inoremap \\bfu 𝐮
inoremap \\bfv 𝐯
inoremap \\bfw 𝐰
inoremap \\bfx 𝐱
inoremap \\bfy 𝐲
inoremap \\bfz 𝐳
inoremap \\bf0 𝟎
inoremap \\bf1 𝟏
inoremap \\bf2 𝟐
inoremap \\bf3 𝟑
inoremap \\bf4 𝟒
inoremap \\bf5 𝟓
inoremap \\bf6 𝟔
inoremap \\bf7 𝟕
inoremap \\bf8 𝟖
inoremap \\bf9 𝟗
inoremap \\bfiA 𝑨
inoremap \\bfiB 𝑩
inoremap \\bfiC 𝑪
inoremap \\bfiD 𝑫
inoremap \\bfiE 𝑬
inoremap \\bfiF 𝑭
inoremap \\bfiG 𝑮
inoremap \\bfiH 𝑯
inoremap \\bfiI 𝑰
inoremap \\bfiJ 𝑱
inoremap \\bfiK 𝑲
inoremap \\bfiL 𝑳
inoremap \\bfiM 𝑴
inoremap \\bfiN 𝑵
inoremap \\bfiO 𝑶
inoremap \\bfiP 𝑷
inoremap \\bfiQ 𝑸
inoremap \\bfiR 𝑹
inoremap \\bfiS 𝑺
inoremap \\bfiT 𝑻
inoremap \\bfiU 𝑼
inoremap \\bfiV 𝑽
inoremap \\bfiW 𝑾
inoremap \\bfiX 𝑿
inoremap \\bfiY 𝒀
inoremap \\bfiZ 𝒁
inoremap \\bfia 𝒂
inoremap \\bfib 𝒃
inoremap \\bfic 𝒄
inoremap \\bfid 𝒅
inoremap \\bfie 𝒆
inoremap \\bfif 𝒇
inoremap \\bfig 𝒈
inoremap \\bfih 𝒉
inoremap \\bfii 𝒊
inoremap \\bfij 𝒋
inoremap \\bfik 𝒌
inoremap \\bfil 𝒍
inoremap \\bfim 𝒎
inoremap \\bfin 𝒏
inoremap \\bfio 𝒐
inoremap \\bfip 𝒑
inoremap \\bfiq 𝒒
inoremap \\bfir 𝒓
inoremap \\bfis 𝒔
inoremap \\bfit 𝒕
inoremap \\bfiu 𝒖
inoremap \\bfiv 𝒗
inoremap \\bfiw 𝒘
inoremap \\bfix 𝒙
inoremap \\bfiy 𝒚
inoremap \\bfiz 𝒛
inoremap \\bsA 𝗔
inoremap \\bsB 𝗕
inoremap \\bsC 𝗖
inoremap \\bsD 𝗗
inoremap \\bsE 𝗘
inoremap \\bsF 𝗙
inoremap \\bsG 𝗚
inoremap \\bsH 𝗛
inoremap \\bsI 𝗜
inoremap \\bsJ 𝗝
inoremap \\bsK 𝗞
inoremap \\bsL 𝗟
inoremap \\bsM 𝗠
inoremap \\bsN 𝗡
inoremap \\bsO 𝗢
inoremap \\bsP 𝗣
inoremap \\bsQ 𝗤
inoremap \\bsR 𝗥
inoremap \\bsS 𝗦
inoremap \\bsT 𝗧
inoremap \\bsU 𝗨
inoremap \\bsV 𝗩
inoremap \\bsW 𝗪
inoremap \\bsX 𝗫
inoremap \\bsY 𝗬
inoremap \\bsZ 𝗭
inoremap \\bsa 𝗮
inoremap \\bsb 𝗯
inoremap \\bsc 𝗰
inoremap \\bsd 𝗱
inoremap \\bse 𝗲
inoremap \\bsf 𝗳
inoremap \\bsg 𝗴
inoremap \\bsh 𝗵
inoremap \\bsi 𝗶
inoremap \\bsj 𝗷
inoremap \\bsk 𝗸
inoremap \\bsl 𝗹
inoremap \\bsm 𝗺
inoremap \\bsn 𝗻
inoremap \\bso 𝗼
inoremap \\bsp 𝗽
inoremap \\bsq 𝗾
inoremap \\bsr 𝗿
inoremap \\bss 𝘀
inoremap \\bst 𝘁
inoremap \\bsu 𝘂
inoremap \\bsv 𝘃
inoremap \\bsw 𝘄
inoremap \\bsx 𝘅
inoremap \\bsy 𝘆
inoremap \\bsz 𝘇
inoremap \\bs0 𝟬
inoremap \\bs1 𝟭
inoremap \\bs2 𝟮
inoremap \\bs3 𝟯
inoremap \\bs4 𝟰
inoremap \\bs5 𝟱
inoremap \\bs6 𝟲
inoremap \\bs7 𝟳
inoremap \\bs8 𝟴
inoremap \\bs9 𝟵
inoremap \\bsiA 𝘼
inoremap \\bsiB 𝘽
inoremap \\bsiC 𝘾
inoremap \\bsiD 𝘿
inoremap \\bsiE 𝙀
inoremap \\bsiF 𝙁
inoremap \\bsiG 𝙂
inoremap \\bsiH 𝙃
inoremap \\bsiI 𝙄
inoremap \\bsiJ 𝙅
inoremap \\bsiK 𝙆
inoremap \\bsiL 𝙇
inoremap \\bsiM 𝙈
inoremap \\bsiN 𝙉
inoremap \\bsiO 𝙊
inoremap \\bsiP 𝙋
inoremap \\bsiQ 𝙌
inoremap \\bsiR 𝙍
inoremap \\bsiS 𝙎
inoremap \\bsiT 𝙏
inoremap \\bsiU 𝙐
inoremap \\bsiV 𝙑
inoremap \\bsiW 𝙒
inoremap \\bsiX 𝙓
inoremap \\bsiY 𝙔
inoremap \\bsiZ 𝙕
inoremap \\bsia 𝙖
inoremap \\bsib 𝙗
inoremap \\bsic 𝙘
inoremap \\bsid 𝙙
inoremap \\bsie 𝙚
inoremap \\bsif 𝙛
inoremap \\bsig 𝙜
inoremap \\bsih 𝙝
inoremap \\bsii 𝙞
inoremap \\bsij 𝙟
inoremap \\bsik 𝙠
inoremap \\bsil 𝙡
inoremap \\bsim 𝙢
inoremap \\bsin 𝙣
inoremap \\bsio 𝙤
inoremap \\bsip 𝙥
inoremap \\bsiq 𝙦
inoremap \\bsir 𝙧
inoremap \\bsis 𝙨
inoremap \\bsit 𝙩
inoremap \\bsiu 𝙪
inoremap \\bsiv 𝙫
inoremap \\bsiw 𝙬
inoremap \\bsix 𝙭
inoremap \\bsiy 𝙮
inoremap \\bsiz 𝙯
inoremap \\bbA 𝔸
inoremap \\bbB 𝔹
inoremap \\bbC ℂ
inoremap \\bbD 𝔻
inoremap \\bbE 𝔼
inoremap \\bbF 𝔽
inoremap \\bbG 𝔾
inoremap \\bbH ℍ
inoremap \\bbI 𝕀
inoremap \\bbJ 𝕁
inoremap \\bbK 𝕂
inoremap \\bbL 𝕃
inoremap \\bbM 𝕄
inoremap \\bbN ℕ
inoremap \\bbO 𝕆
inoremap \\bbP ℙ
inoremap \\bbQ ℚ
inoremap \\bbR ℝ
inoremap \\bbS 𝕊
inoremap \\bbT 𝕋
inoremap \\bbU 𝕌
inoremap \\bbV 𝕍
inoremap \\bbW 𝕎
inoremap \\bbX 𝕏
inoremap \\bbY 𝕐
inoremap \\bbZ ℤ
inoremap \\bba 𝕒
inoremap \\bbb 𝕓
inoremap \\bbc 𝕔
inoremap \\bbd 𝕕
inoremap \\bbe 𝕖
inoremap \\bbf 𝕗
inoremap \\bbg 𝕘
inoremap \\bbh 𝕙
inoremap \\bbi 𝕚
inoremap \\bbj 𝕛
inoremap \\bbk 𝕜
inoremap \\bbl 𝕝
inoremap \\bbm 𝕞
inoremap \\bbn 𝕟
inoremap \\bbo 𝕠
inoremap \\bbp 𝕡
inoremap \\bbq 𝕢
inoremap \\bbr 𝕣
inoremap \\bbs 𝕤
inoremap \\bbt 𝕥
inoremap \\bbu 𝕦
inoremap \\bbv 𝕧
inoremap \\bbw 𝕨
inoremap \\bbx 𝕩
inoremap \\bby 𝕪
inoremap \\bbz 𝕫
inoremap \\bb0 𝟘
inoremap \\bb1 𝟙
inoremap \\bb2 𝟚
inoremap \\bb3 𝟛
inoremap \\bb4 𝟜
inoremap \\bb5 𝟝
inoremap \\bb6 𝟞
inoremap \\bb7 𝟟
inoremap \\bb8 𝟠
inoremap \\bb9 𝟡
inoremap \\bbiD ⅅ
inoremap \\bbid ⅆ
inoremap \\bbie ⅇ
inoremap \\bbii ⅈ
inoremap \\bbij ⅉ
inoremap \\bbGam ℾ
inoremap \\bbPi ℿ
inoremap \\bbSig ⅀
inoremap \\bbgam ℽ
inoremap \\bbpi ℼ
inoremap \\frakA 𝔄
inoremap \\frakB 𝔅
inoremap \\frakC ℭ
inoremap \\frakD 𝔇
inoremap \\frakE 𝔈
inoremap \\frakF 𝔉
inoremap \\frakG 𝔊
inoremap \\frakH ℌ
inoremap \\frakI ℑ
inoremap \\frakJ 𝔍
inoremap \\frakK 𝔎
inoremap \\frakL 𝔏
inoremap \\frakM 𝔐
inoremap \\frakN 𝔑
inoremap \\frakO 𝔒
inoremap \\frakP 𝔓
inoremap \\frakQ 𝔔
inoremap \\frakR ℜ
inoremap \\frakS 𝔖
inoremap \\frakT 𝔗
inoremap \\frakU 𝔘
inoremap \\frakV 𝔙
inoremap \\frakW 𝔚
inoremap \\frakX 𝔛
inoremap \\frakY 𝔜
inoremap \\frakZ ℨ
inoremap \\fraka 𝔞
inoremap \\frakb 𝔟
inoremap \\frakc 𝔠
inoremap \\frakd 𝔡
inoremap \\frake 𝔢
inoremap \\frakf 𝔣
inoremap \\frakg 𝔤
inoremap \\frakh 𝔥
inoremap \\fraki 𝔦
inoremap \\frakj 𝔧
inoremap \\frakk 𝔨
inoremap \\frakl 𝔩
inoremap \\frakm 𝔪
inoremap \\frakn 𝔫
inoremap \\frako 𝔬
inoremap \\frakp 𝔭
inoremap \\frakq 𝔮
inoremap \\frakr 𝔯
inoremap \\fraks 𝔰
inoremap \\frakt 𝔱
inoremap \\fraku 𝔲
inoremap \\frakv 𝔳
inoremap \\frakw 𝔴
inoremap \\frakx 𝔵
inoremap \\fraky 𝔶
inoremap \\frakz 𝔷
inoremap \\bfrakA 𝕬
inoremap \\bfrakB 𝕭
inoremap \\bfrakC 𝕮
inoremap \\bfrakD 𝕯
inoremap \\bfrakE 𝕰
inoremap \\bfrakF 𝕱
inoremap \\bfrakG 𝕲
inoremap \\bfrakH 𝕳
inoremap \\bfrakI 𝕴
inoremap \\bfrakJ 𝕵
inoremap \\bfrakK 𝕶
inoremap \\bfrakL 𝕷
inoremap \\bfrakM 𝕸
inoremap \\bfrakN 𝕹
inoremap \\bfrakO 𝕺
inoremap \\bfrakP 𝕻
inoremap \\bfrakQ 𝕼
inoremap \\bfrakR 𝕽
inoremap \\bfrakS 𝕾
inoremap \\bfrakT 𝕿
inoremap \\bfrakU 𝖀
inoremap \\bfrakV 𝖁
inoremap \\bfrakW 𝖂
inoremap \\bfrakX 𝖃
inoremap \\bfrakY 𝖄
inoremap \\bfrakZ 𝖅
inoremap \\bfraka 𝖆
inoremap \\bfrakb 𝖇
inoremap \\bfrakc 𝖈
inoremap \\bfrakd 𝖉
inoremap \\bfrake 𝖊
inoremap \\bfrakf 𝖋
inoremap \\bfrakg 𝖌
inoremap \\bfrakh 𝖍
inoremap \\bfraki 𝖎
inoremap \\bfrakj 𝖏
inoremap \\bfrakk 𝖐
inoremap \\bfrakl 𝖑
inoremap \\bfrakm 𝖒
inoremap \\bfrakn 𝖓
inoremap \\bfrako 𝖔
inoremap \\bfrakp 𝖕
inoremap \\bfrakq 𝖖
inoremap \\bfrakr 𝖗
inoremap \\bfraks 𝖘
inoremap \\bfrakt 𝖙
inoremap \\bfraku 𝖚
inoremap \\bfrakv 𝖛
inoremap \\bfrakw 𝖜
inoremap \\bfrakx 𝖝
inoremap \\bfraky 𝖞
inoremap \\bfrakz 𝖟
inoremap \\^0 ⁰
inoremap \\^1 ¹
inoremap \\^2 ²
inoremap \\^3 ³
inoremap \\^4 ⁴
inoremap \\^5 ⁵
inoremap \\^6 ⁶
inoremap \\^7 ⁷
inoremap \\^8 ⁸
inoremap \\^9 ⁹
inoremap \\^+ ⁺
inoremap \\^- ⁻
inoremap \\^= ⁼
inoremap \\^( ⁽
inoremap \\^) ⁾
inoremap \\^A ᴬ
inoremap \\^B ᴮ
inoremap \\^D ᴰ
inoremap \\^E ᴱ
inoremap \\^G ᴳ
inoremap \\^H ᴴ
inoremap \\^I ᴵ
inoremap \\^J ᴶ
inoremap \\^K ᴷ
inoremap \\^L ᴸ
inoremap \\^M ᴹ
inoremap \\^N ᴺ
inoremap \\^O ᴼ
inoremap \\^P ᴾ
inoremap \\^R ᴿ
inoremap \\^T ᵀ
inoremap \\^U ᵁ
inoremap \\^V ⱽ
inoremap \\^W ᵂ
inoremap \\^a ᵃ
inoremap \\^b ᵇ
inoremap \\^c ᶜ
inoremap \\^d ᵈ
inoremap \\^e ᵉ
inoremap \\^f ᶠ
inoremap \\^g ᵍ
inoremap \\^h ʰ
inoremap \\^i ⁱ
inoremap \\^j ʲ
inoremap \\^k ᵏ
inoremap \\^l ˡ
inoremap \\^m ᵐ
inoremap \\^n ⁿ
inoremap \\^o ᵒ
inoremap \\^p ᵖ
inoremap \\^r ʳ
inoremap \\^s ˢ
inoremap \\^t ᵗ
inoremap \\^u ᵘ
inoremap \\^v ᵛ
inoremap \\^w ʷ
inoremap \\^x ˣ
inoremap \\^y ʸ
inoremap \\^z ᶻ
inoremap \\_0 ₀
inoremap \\_1 ₁
inoremap \\_2 ₂
inoremap \\_3 ₃
inoremap \\_4 ₄
inoremap \\_5 ₅
inoremap \\_6 ₆
inoremap \\_7 ₇
inoremap \\_8 ₈
inoremap \\_9 ₉
inoremap \\_+ ₊
inoremap \\_- ₋
inoremap \\_= ₌
inoremap \\_( ₍
inoremap \\_) ₎
inoremap \\_a ₐ
inoremap \\_e ₑ
inoremap \\_h ₕ
inoremap \\_i ᵢ
inoremap \\_j ⱼ
inoremap \\_k ₖ
inoremap \\_l ₗ
inoremap \\_m ₘ
inoremap \\_n ₙ
inoremap \\_o ₒ
inoremap \\_p ₚ
inoremap \\_r ᵣ
inoremap \\_s ₛ
inoremap \\_t ₜ
inoremap \\_u ᵤ
inoremap \\_v ᵥ
inoremap \\_x ₓ
inoremap \\blank ⠀
inoremap \\Alpha Α
inoremap \\Beta Β
inoremap \\Gamma Γ
inoremap \\Delta Δ
inoremap \\Epsilon Ε
inoremap \\Zeta Ζ
inoremap \\Eta Η
inoremap \\Theta Θ
inoremap \\Iota Ι
inoremap \\Kappa Κ
inoremap \\Lambda Λ
inoremap \\Mu Μ
inoremap \\Nu Ν
inoremap \\Xi Ξ
inoremap \\Omicron Ο
inoremap \\Pi Π
inoremap \\Rho Ρ
inoremap \\Sigma Σ
inoremap \\Tau Τ
inoremap \\Upsilon Υ
inoremap \\Phi Φ
inoremap \\Chi Χ
inoremap \\Psi Ψ
inoremap \\Omega Ω
inoremap \\alpha α
inoremap \\beta β
inoremap \\curbeta ϐ
inoremap \\gamma γ
inoremap \\delta δ
inoremap \\epsilon ε
inoremap \\lunepsilon ϵ
inoremap \\zeta ζ
inoremap \\eta η
inoremap \\theta ϑ
inoremap \\vtheta θ
inoremap \\iota ι
inoremap \\kappa κ
inoremap \\curkappa ϰ
inoremap \\lambda λ
inoremap \\mu μ
inoremap \\nu ν
inoremap \\xi ξ
inoremap \\omicron ο
inoremap \\pi π
inoremap \\curpi ϖ
inoremap \\rho ρ
inoremap \\currho ϱ
inoremap \\sigma σ
inoremap \\finsigma ς
inoremap \\tau τ
inoremap \\upsilon υ
inoremap \\phi φ
inoremap \\clophi ϕ
inoremap \\chi χ
inoremap \\psi ψ
inoremap \\omega ω
inoremap \\eur €
inoremap \\gbp £
inoremap \\usd $
inoremap \\yen ¥
inoremap \\brl R$
inoremap \\spc ␣
inoremap \\nbsp  
inoremap \\return ⏎
inoremap \\lqua ⌜
inoremap \\rqua ⌝
inoremap \\langle ⟨
inoremap \\rangle ⟩
inoremap \\lceil ⌈
inoremap \\rceil ⌉
inoremap \\lfloor ⌊
inoremap \\rfloor ⌋
inoremap \\lbag ⟅
inoremap \\rbag ⟆
inoremap \\lsem ⟦
inoremap \\rsem ⟧
inoremap \\lSet ⦃
inoremap \\rSet ⦄
inoremap \\lPar ⦅
inoremap \\rPar ⦆
inoremap \\lban ⦇
inoremap \\rban ⦈
inoremap \\lAngle ⦉
inoremap \\rAngle ⦊
inoremap \\lnorm ‖
inoremap \\rnorm ‖
inoremap \\halmos ∎
inoremap \\qed ∎
inoremap \\leq ≤
inoremap \\geq ≥
inoremap \\neq ≠
inoremap \\nlt ≮
inoremap \\ngt ≯
inoremap \\nleq ≰
inoremap \\ngeq ≱
inoremap \\div ∣
inoremap \\ndiv ∤
inoremap \\forall ∀
inoremap \\exists ∃
inoremap \\nexists ∄
inoremap \\implies ⇒
inoremap \\implied ⇐
inoremap \\iff ⇔
inoremap \\timplies ⟹
inoremap \\timplied ⟸
inoremap \\tiff ⟺
inoremap \\vimplies ⇓
inoremap \\vimplied ⇑
inoremap \\viff ⇕
inoremap \\rlarr ⇄
inoremap \\lrarr ⇆
inoremap \\tofrom ⇄
inoremap \\fromto ⇆
inoremap \\udarr ⇅
inoremap \\uuarr ⇈
inoremap \\ddarr ⇊
inoremap \\llarr ⇇
inoremap \\rrarr ⇉
inoremap \\nimplied ⇍
inoremap \\nimplies ⇏
inoremap \\niff ⇎
inoremap \\inteq ≡
inoremap \\intneq ≢
inoremap \\defeq ≝
inoremap \\doteq ≐
inoremap \\askeq ≟
inoremap \\asteq ⩮
inoremap \\stareq ≛
inoremap \\defiff ⇐≝⇒
inoremap \\intiff ⇚⇛
inoremap \\intimplies ⇛
inoremap \\vintimplied ⤊
inoremap \\vintimplies ⤋
inoremap \\intimplied ⇚
inoremap \\ledfrom ↜
inoremap \\leadsto ↝
inoremap \\rleads ↝
inoremap \\lleads ↜
inoremap \\eqto ⥱
inoremap \\isoto ⥲
inoremap \\Funto ⥤
inoremap \\therefore ∴
inoremap \\because ∵
inoremap \\vdots ⋮
inoremap \\hdots ⋯
inoremap \\cdots ⋯
inoremap \\dotsb ⋯
inoremap \\ldots …
inoremap \\dotsc …
inoremap \\pm ±
inoremap \\mp ∓
inoremap \\infty ∞
inoremap \\pinfty +∞
inoremap \\minfty -∞
inoremap \\pminfty ±∞
inoremap \\mpinfty ∓∞
inoremap \\surd √
inoremap \\integ ∫
inoremap \\iinteg ∬
inoremap \\iiinteg ∭
inoremap \\ointeg ∮
inoremap \\nabla ∇
inoremap \\partial ∂
inoremap \\ast ∗
inoremap \\star ⋆
inoremap \\bullet ∙
inoremap \\cdot ·
inoremap \\ntimes ·
inoremap \\cross ×
inoremap \\times ×
inoremap \\circ ∘
inoremap \\oplus ⊕
inoremap \\ominus ⊖
inoremap \\otimes ⊗
inoremap \\tensor ⊗
inoremap \\ocross ⊗
inoremap \\odiv ⊘
inoremap \\odot ⊙
inoremap \\dotminus ∸
inoremap \\monus ∸
inoremap \\uplus ⊎
inoremap \\Uplus ⨄
inoremap \\dhole –
inoremap \\hole _
inoremap \\emptyset Ø
inoremap \\empty Ø
inoremap \\bools 𝔹
inoremap \\nats ℕ
inoremap \\ints ℤ
inoremap \\rats ℚ
inoremap \\reals ℝ
inoremap \\complex ℂ
inoremap \\in ∈
inoremap \\notin ∉
inoremap \\nin ∉
inoremap \\ni ∋
inoremap \\notni ∌
inoremap \\nni ∌
inoremap \\Inter ⋂
inoremap \\Union ⋃
inoremap \\inter ∩
inoremap \\union ∪
inoremap \\disjunion ⊎
inoremap \\Disjunion ⨄
inoremap \\dunion ⊎
inoremap \\Dunion ⨄
inoremap \\symdiff ∆
inoremap \\sdiff ∆
inoremap \\setminus ∖
inoremap \\minus ∖
inoremap \\subset ⊆
inoremap \\supset ⊇
inoremap \\psubset ⊊
inoremap \\psupset ⊋
inoremap \\hsubset ⊂
inoremap \\hsupset ⊃
inoremap \\nsubset ⊈
inoremap \\nsupset ⊉
inoremap \\subsetneq ⊊
inoremap \\supsetneq ⊋
inoremap \\sqleq ⊑
inoremap \\sqgeq ⊒
inoremap \\sqlt ⊏
inoremap \\sqgt ⊐
inoremap \\sqlneq ⋤
inoremap \\sqgneq ⋥
inoremap \\sqnleq ⋢
inoremap \\sqngeq ⋣
inoremap \\semleq ⊑
inoremap \\semgeq ⊒
inoremap \\semlneq ⋤
inoremap \\semgneq ⋥
inoremap \\nsemleq ⋢
inoremap \\nsemgeq ⋣
inoremap \\domleq ⊑
inoremap \\domgeq ⊒
inoremap \\domlneq ⋤
inoremap \\domgneq ⋥
inoremap \\pset ℘
inoremap \\aleph ℵ
inoremap \\beth ℶ
inoremap \\gimel ℷ
inoremap \\comp ∘
inoremap \\to →
inoremap \\from ←
inoremap \\nto ↛
inoremap \\nfrom ↚
inoremap \\parto ⇀
inoremap \\mapsto ↦
inoremap \\mapsfrom ↤
inoremap \\tmapsto ⟼
inoremap \\tmapsfrom ⟻
inoremap \\mapsup ↥
inoremap \\mapsdown ↧
inoremap \\parfrom ↼
inoremap \\rest ↾
inoremap \\surto ↠
inoremap \\surfrom ↞
inoremap \\injto ↣
inoremap \\injfrom ↢
inoremap \\embto ↪
inoremap \\embfrom ↩
inoremap \\bijto ⤖
inoremap \\relto ⇾
inoremap \\relfrom ⇽
inoremap \\dual ∂
inoremap \\ndetfrom ⇜
inoremap \\ndetto ⇝
inoremap \\dfrom ⇠
inoremap \\dto ⇢
inoremap \\equiv ≅
inoremap \\nequiv ≇
inoremap \\iso ≅
inoremap \\niso ≇
inoremap \\rcomp ⋄
inoremap \\cong ≡
inoremap \\ncong ≢
inoremap \\normal ⊴
inoremap \\pnormal ⊲
inoremap \\sim ~
inoremap \\nsim ≁
inoremap \\approx ≈
inoremap \\napprox ≉
inoremap \\Prod ∏
inoremap \\Coprod ∐
inoremap \\coprod ⨿
inoremap \\Sum ∑
inoremap \\op ᵒᵖ
inoremap \\cons ∷
inoremap \\concat ⧺
inoremap \\:: ∷
inoremap \\inv ⁻¹
inoremap \\lnot ¬
inoremap \\lforall ∀
inoremap \\lexists ∃
inoremap \\limplies →
inoremap \\limplied ←
inoremap \\liff ↔
inoremap \\land ∧
inoremap \\lor ∨
inoremap \\Land ⋀
inoremap \\Lor ⋁
inoremap \\sequent ⊢
inoremap \\proves ⊢
inoremap \\nproves ⊬
inoremap \\models ⊨
inoremap \\nmodels ⊭
inoremap \\forces ⊩
inoremap \\nforces ⊮
inoremap \\linnot ⊥
inoremap \\linto ⊸
inoremap \\linwith &
inoremap \\linpar ⅋
inoremap \\himplies ⥰
inoremap \\horse ⥰
inoremap \\top ⊤
inoremap \\bottom ⊥
inoremap \\Meet ⋀
inoremap \\Join ⋁
inoremap \\meet ∧
inoremap \\join ∨
inoremap \\incompar ≸
inoremap \\incompat ‖
inoremap \\wbelow ≪
inoremap \\wabove ≫
inoremap \\domlt ⊏
inoremap \\domgt ⊐
inoremap \\domleq ⊑
inoremap \\domgeq ⊒
inoremap \\glb ⊓
inoremap \\lub ⊔
inoremap \\Glb ⨅
inoremap \\Lub ⨆
inoremap \\spades ♠
inoremap \\hearts ♡
inoremap \\diamonds ♢
inoremap \\clubs ♣
inoremap \\magic ⛤
inoremap \\rturnstile ⊢
inoremap \\lturnstile ⊣
inoremap \\sqleftarrow ⇜
inoremap \\sqrightarrow ⇝
inoremap \\sqbotharrow ↭
inoremap \\nwarrow ↖
inoremap \\nearrow ↗
inoremap \\swarrow ↙
inoremap \\searrow ↘
inoremap \\duparrow ⇡
inoremap \\drightarrow ⇢
inoremap \\ddownarrow ⇣
inoremap \\dleftarrow ⇠
inoremap \\up ↑
inoremap \\down ↓
inoremap \\Ell ℒ
inoremap \\ell ℓ
inoremap \\bang !
inoremap \\gnab ¡
inoremap \\bbang ‼
inoremap \\ibang ‽
inoremap \\ignab ⸘
inoremap \\abang ⁈
inoremap \\bask ⁉
inoremap \\frown ⌢
inoremap \\smile ⌣
inoremap \\utri △
inoremap \\dtri ▽
inoremap \\ltri ◁
inoremap \\rtri ▷
inoremap \\utris ▵
inoremap \\dtris ▿
inoremap \\ltris ◃
inoremap \\rtris ▹
inoremap \\ubtri ▲
inoremap \\dbtri ▼
inoremap \\lbtri ◄
inoremap \\rbtri ►
inoremap \\ubtris ▴
inoremap \\dbtris ▾
inoremap \\lbtris ◂
inoremap \\rbtris ▸
inoremap \\CAT 𝐂𝐚𝐭
inoremap \\SET 𝐒𝐞𝐭
inoremap \\PSET 𝐏𝐒𝐞𝐭
inoremap \\PTDSET 𝐏𝐭𝐝𝐒𝐞𝐭
inoremap \\FINSET 𝐅𝐢𝐧𝐒𝐞𝐭
inoremap \\FINORD 𝐅𝐢𝐧𝐎𝐫𝐝
inoremap \\ORD 𝐎𝐫𝐝
inoremap \\PROSET 𝐏𝐫𝐨𝐬𝐞𝐭
inoremap \\POSET 𝐏𝐨𝐬𝐞𝐭
inoremap \\SGROUP 𝐒𝐞𝐦𝐢𝐠𝐫𝐨𝐮𝐩
inoremap \\SGRP 𝐒𝐞𝐦𝐢𝐠𝐫𝐩
inoremap \\MON 𝐌𝐨𝐧
inoremap \\MONOID 𝐌𝐨𝐧𝐨𝐢𝐝
inoremap \\GROUP 𝐆𝐫𝐨𝐮𝐩
inoremap \\GRP 𝐆𝐫𝐩
inoremap \\ABEL 𝐀𝐛𝐞𝐥
inoremap \\RING 𝐑𝐢𝐧𝐠
inoremap \\RNG 𝐑𝐧𝐠
inoremap \\RIG 𝐑𝐢𝐠
inoremap \\MOD 𝐌𝐨𝐝
inoremap \\MAT 𝐌𝐚𝐭𝐫𝐢𝐱
inoremap \\LAT 𝐋𝐚𝐭𝐭𝐢𝐜𝐞
inoremap \\HALG 𝐇𝐞𝐲𝐭𝐢𝐧𝐠
inoremap \\BALG 𝐁𝐨𝐨𝐥𝐞𝐚𝐧
inoremap \\HA 𝐇𝐀
inoremap \\BA 𝐁𝐀
inoremap \\MODEL 𝐌𝐨𝐝𝐞𝐥
inoremap \\psubs ⊊
inoremap \\psups ⊋
inoremap \\hsubs ⊂
inoremap \\hsups ⊃
inoremap \\nsubs ⊈
inoremap \\nsups ⊉
inoremap \\subsne ⊊
inoremap \\supsne ⊋
inoremap \\fa ∀
inoremap \\ex ∃
inoremap \\nex ∄
inoremap \\imps ⇒
inoremap \\impd ⇐
inoremap \\iff ⇔
inoremap \\timps ⟹
inoremap \\timpd ⟸
inoremap \\tiff ⟺
inoremap \\vimps ⇓
inoremap \\vimpd ⇑
inoremap \\nimpd ⇍
inoremap \\nimps ⇏
inoremap \\rmaps ↦
inoremap \\lmaps ↤
inoremap \\Rmaps ⟼
inoremap \\Lmaps ⟻
inoremap \\there ∴
inoremap \\cause ∵
